export {default as Navbar} from '../components/Navbar.vue'
export {default as Sidebar} from '../components/sidebar/Sidebar.vue'
export {default as Register} from '../components/Register.vue'
export {default as Login} from '../components/Login.vue'
export {default as Admin} from '../components/Admin.vue'
