export {default as Navbar} from '../components/Navbar.vue'
export {default as Sidebar} from '../components/Sidebar.vue'
export {default as Register} from '../components/Register.vue'
export {default as AdminDashboard} from '../components/Admin/AdminDashboard.vue'
export {default as StudentDashboard} from '../components/Student/StudentDashboard.vue'
export {default as Login} from '../components/Login.vue'
export {default as SidebarStudent} from '../components/SidebarStudent.vue'
